### ISSUE TITLE
Youtube video missing

### ISSUE THREAD

**Issue by lihengtao** [GATECH-EIC/ViTCoD#1]
Hello. I'm quite interested in your great job.
It seems that you put a youtube video link on your github page. But when I click that link, the content is missing.
Could you fix it please?

**Comment by ranery** [comment]
Hi, thanks for your interests!
While HPCA did not record the presentation. I do have a rehearsal recording at GaTech:

https://drive.google.com/file/d/1b-7r7DutmAnYjOyMLk5uEBFY96XHKMN1/view

I am also planning to record it again to be posted on Youtube, stay tuned.

**Comment by lihengtao** [comment]
It helps a lot. Thank you!

**Comment by ranery** [comment]
I just record it again. Here is the YouTube link:
https://youtu.be/Foyuctc8aPE
