### ISSUE TITLE
Question about V preload cycles in sparse SpMM

### ISSUE THREAD

**Issue by albertface** [GATECH-EIC/ViTCoD#2]
I've noticed that in (ViTCoD/Hardware/Simulator/ViTCoD.py, line 200):
`preload_cycles += my_SRAM.preload_V(nums=head*1* V.shape[1], bits=8)*(1+0.5)`

The preload cycles of V in sparse SpMM are multiplied by (1+0.5). I don't understand where 0.5 comes from. Could you explain it or provide more details?

**Comment by BellXP** [comment]
The Hardware Simulator is not well-organized, can the authors provide clearer code?

**Comment by ranery** [comment]
We've revised the code structure and used hyperparameters to replace hand-defined parameters for a more flexible extension.
